import * as XLSX from "xlsx";
interface Env{DB:D1Database;ASSETS:Fetcher;QIKREACH_USERNAME:string;QIKREACH_PASSWORD:string;QIKREACH_SESSION_SECRET:string}
const E=new TextEncoder(),MAX=10*1024*1024;
const J=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{"content-type":"application/json"}});
const C=(v:unknown)=>v==null?"":String(v).trim();
async function mac(secret:string,value:string){const k=await crypto.subtle.importKey("raw",E.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return [...new Uint8Array(await crypto.subtle.sign("HMAC",k,E.encode(value)))].map(x=>x.toString(16).padStart(2,"0")).join("")}
function cookie(r:Request,name:string){for(const p of (r.headers.get("cookie")||"").split(";")){const [k,...v]=p.trim().split("=");if(k===name)return decodeURIComponent(v.join("="))}return""}
async function auth(r:Request,e:Env){const p=cookie(r,"qikreach_session").split("|");return p.length===3&&p[0]===e.QIKREACH_USERNAME&&+p[1]>Date.now()/1000&&p[2]===await mac(e.QIKREACH_SESSION_SECRET,`${p[0]}|${p[1]}`)}
const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,"");
function val(row:Record<string,unknown>,...names:string[]){const wanted=new Set(names.map(norm)),key=Object.keys(row).find(k=>wanted.has(norm(k)));return C(key?row[key]:"")}
function phone(v:string){const seen=new Set<string>();return v.split(/[|,;\n]+/).map(x=>{let d=x.replace(/\D/g,"");if(d.length===11&&d[0]==="1")d=d.slice(1);return d.length===10?`+1${d}`:""}).filter(x=>x&&!seen.has(x)&&seen.add(x)).join(" | ")}
function email(v:string){return [...new Set(v.toLowerCase().match(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/g)||[])].join(" | ")}
async function sha(v:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",E.encode(v)))].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function api(r:Request,e:Env,u:URL){if(!await auth(r,e))return J({error:"Authentication required"},401);if(u.pathname==="/api/health")return J({ok:true});if(u.pathname==="/api/search"&&r.method==="POST"){const b=await r.json<{query?:string}>(),q=`%${C(b.query)}%`,x=await e.DB.prepare("SELECT * FROM master_leads WHERE company_name LIKE ? OR owner_name LIKE ? OR all_phones LIKE ? OR all_emails LIKE ? OR ein LIKE ? ORDER BY updated_at DESC LIMIT 100").bind(q,q,q,q,q).all();return J({results:x.results})}if(u.pathname==="/api/batch"&&r.method==="POST"){const f=(await r.formData()).get("file");if(!(f instanceof File)||!f.name.toLowerCase().endsWith(".xlsx"))return J({error:"Select an .xlsx file"},400);if(f.size>MAX)return J({error:"Maximum upload is 10 MiB"},413);const w=XLSX.read(await f.arrayBuffer(),{type:"array"}),rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(w.Sheets[w.SheetNames[0]],{defval:""});if(rows.length>1000)return J({error:"Maximum batch is 1,000 rows"},413);const out=[];for(const row of rows){const company=val(row,"company","company name","business name"),owner=val(row,"owner","owner name","contact","contact name","name"),phones=phone(val(row,"phone","phones","phone number","mobile")),emails=email(val(row,"email","emails","email address")),ein=val(row,"ein"),lead=[await sha([company,owner,phones,emails,ein].join("|").toLowerCase()||crypto.randomUUID()),company,owner,val(row,"revenue","monthly revenue","annual revenue"),val(row,"address","business address"),val(row,"dob","date of birth"),val(row,"ssn"),ein,val(row,"start date","business start date"),phones,emails,"uploaded spreadsheet"];await e.DB.prepare("INSERT INTO master_leads VALUES (?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(lead_hash) DO UPDATE SET company_name=excluded.company_name,owner_name=excluded.owner_name,revenue=excluded.revenue,address=excluded.address,dob=excluded.dob,ssn=excluded.ssn,ein=excluded.ein,start_date=excluded.start_date,all_phones=excluded.all_phones,all_emails=excluded.all_emails,sources=excluded.sources,updated_at=CURRENT_TIMESTAMP").bind(...lead).run();out.push({...row,"Normalized Phones":phones,"Validated Emails":emails,"QikReach Sources":"uploaded spreadsheet"})}const o=XLSX.utils.book_new();XLSX.utils.book_append_sheet(o,XLSX.utils.json_to_sheet(out),"Enriched Leads");return new Response(XLSX.write(o,{bookType:"xlsx",type:"array"}),{headers:{"content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename="qikreach-enriched-${Date.now()}.xlsx"`}})}return J({error:"Not found"},404)}
export default{async fetch(r:Request,e:Env){const u=new URL(r.url);if(!e.QIKREACH_PASSWORD||!e.QIKREACH_SESSION_SECRET)return new Response("Missing required secrets",{status:500});if(u.pathname==="/login"&&r.method==="POST"){const f=await r.formData();if(C(f.get("username"))!==e.QIKREACH_USERNAME||C(f.get("password"))!==e.QIKREACH_PASSWORD)return Response.redirect(new URL("/?error=1",u),303);const exp=Math.floor(Date.now()/1000)+43200,body=`${e.QIKREACH_USERNAME}|${exp}`,token=`${body}|${await mac(e.QIKREACH_SESSION_SECRET,body)}`;return new Response(null,{status:303,headers:{location:"/","set-cookie":`qikreach_session=${encodeURIComponent(token)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`}})}if(u.pathname==="/logout")return new Response(null,{status:303,headers:{location:"/","set-cookie":"qikreach_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0"}});if(u.pathname.startsWith("/api/"))return api(r,e,u);if(!await auth(r,e))return e.ASSETS.fetch(new Request(new URL("/login.html",u),r));return e.ASSETS.fetch(r)}} satisfies ExportedHandler<Env>;
