import * as XLSX from "xlsx";
interface Env{DB:D1Database;ASSETS:Fetcher;QIKREACH_USERNAME:string;QIKREACH_PASSWORD:string;QIKREACH_SESSION_SECRET:string}
const E=new TextEncoder(),MAX=10*1024*1024;
const J=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store"}});
const C=(v:unknown)=>v==null?"":String(v).trim();
async function mac(secret:string,value:string){const k=await crypto.subtle.importKey("raw",E.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return [...new Uint8Array(await crypto.subtle.sign("HMAC",k,E.encode(value)))].map(x=>x.toString(16).padStart(2,"0")).join("")}
function cookie(r:Request,name:string){for(const p of (r.headers.get("cookie")||"").split(";")){const [k,...v]=p.trim().split("=");if(k===name)return decodeURIComponent(v.join("="))}return""}
async function auth(r:Request,e:Env){const p=cookie(r,"qikreach_session").split("|");return p.length===3&&p[0]===e.QIKREACH_USERNAME&&+p[1]>Date.now()/1000&&p[2]===await mac(e.QIKREACH_SESSION_SECRET,`${p[0]}|${p[1]}`)}
const norm=(s:string)=>C(s).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ");
const compact=(s:string)=>norm(s).replace(/\s/g,"");
const onlyDigits=(s:string)=>C(s).replace(/[^0-9]/g,"").replace(/^1([0-9]{10})$/,"$1");
function val(row:Record<string,unknown>,...names:string[]){const wanted=new Set(names.map(compact)),key=Object.keys(row).find(k=>wanted.has(compact(k)));return C(key?row[key]:"")}
function phone(v:string){const seen=new Set<string>();return C(v).split(/[|,;\n]+/).map(x=>{let d=x.replace(/[^0-9]/g,"");if(d.length===11&&d.startsWith("1"))d=d.slice(1);return d.length===10?`+1${d}`:""}).filter(x=>x&&!seen.has(x)&&seen.add(x)).join(" | ")}
function email(v:string){return [...new Set(C(v).toLowerCase().match(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/g)||[])].join(" | ")}
function distance(a:string,b:string){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;const prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let left=i,diag=i-1;for(let j=1;j<=b.length;j++){const up=prev[j],next=a[i-1]===b[j-1]?diag:Math.min(diag,up,left)+1;diag=up;prev[j]=next;left=next}}return prev[b.length]}
function fieldScore(query:string,value:string){const q=norm(query),v=norm(value),qc=compact(query),vc=compact(value);if(!q||!v)return 0;if(q===v||qc===vc)return 100;if(v.includes(q)||vc.includes(qc))return 85;if(q.includes(v)&&v.length>=4)return 70;const tokens=q.split(" ").filter(Boolean),matched=tokens.filter(t=>v.includes(t)).length;if(tokens.length&&matched===tokens.length)return 75;if(tokens.length&&matched)return 35+Math.round(30*matched/tokens.length);if(q.length>=4&&v.length>=4){const d=distance(q.slice(0,64),v.slice(0,64)),ratio=1-d/Math.max(q.length,v.length);if(ratio>=.82)return Math.round(60*ratio);if(ratio>=.68)return Math.round(40*ratio)}return 0}
function scoreLead(query:string,row:Record<string,unknown>){const qDigits=onlyDigits(query),qEmail=C(query).toLowerCase().replace(/\s/g,"");let score=0;if(qDigits.length>=4){const p=onlyDigits(C(row.all_phones)),e=onlyDigits(C(row.ein));if(p.includes(qDigits)||e.includes(qDigits))score=Math.max(score,qDigits.length>=9?100:80)}if(qEmail.includes("@")&&C(row.all_emails).toLowerCase().includes(qEmail))score=100;for(const key of ["company_name","owner_name","all_emails","address","ein"]){score=Math.max(score,fieldScore(query,C(row[key])))}return score}
async function sha(v:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",E.encode(v)))].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function api(r:Request,e:Env,u:URL){if(!await auth(r,e))return J({error:"Authentication required"},401);if(u.pathname==="/api/health")return J({ok:true});if(u.pathname==="/api/search"&&r.method==="POST"){try{const b=await r.json() as {query?:string},raw=C(b.query);if(!raw)return J({error:"Enter something to search"},400);const result=await e.DB.prepare("SELECT * FROM master_leads ORDER BY updated_at DESC LIMIT 500").all();const rows=(result.results||[]) as Record<string,unknown>[];const ranked=rows.map(row=>({row,score:scoreLead(raw,row)})).filter(item=>item.score>=28).sort((a,b)=>b.score-a.score).slice(0,100);return J({query:raw,normalized_query:norm(raw),results:ranked.map(item=>({...item.row,match_score:item.score}))})}catch(error){const message=error instanceof Error?error.message:"Search failed";return J({error:`Search could not be completed: ${message}`},500)}}if(u.pathname==="/api/batch"&&r.method==="POST"){const f=(await r.formData()).get("file");if(!(f instanceof File)||!f.name.toLowerCase().endsWith(".xlsx"))return J({error:"Select an .xlsx file"},400);if(f.size>MAX)return J({error:"Maximum upload is 10 MiB"},413);const w=XLSX.read(await f.arrayBuffer(),{type:"array"}),rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(w.Sheets[w.SheetNames[0]],{defval:""});if(rows.length>1000)return J({error:"Maximum batch is 1,000 rows"},413);const out=[];for(const row of rows){const company=val(row,"company","company name","business name"),owner=val(row,"owner","owner name","contact","contact name","name"),phones=phone(val(row,"phone","phones","phone number","mobile")),emails=email(val(row,"email","emails","email address")),ein=val(row,"ein"),lead=[await sha([company,owner,phones,emails,ein].join("|").toLowerCase()||crypto.randomUUID()),company,owner,val(row,"revenue","monthly revenue","annual revenue"),val(row,"address","business address"),val(row,"dob","date of birth"),val(row,"ssn"),ein,val(row,"start date","business start date"),phones,emails,"uploaded spreadsheet"];await e.DB.prepare("INSERT INTO master_leads VALUES (?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(lead_hash) DO UPDATE SET company_name=excluded.company_name,owner_name=excluded.owner_name,revenue=excluded.revenue,address=excluded.address,dob=excluded.dob,ssn=excluded.ssn,ein=excluded.ein,start_date=excluded.start_date,all_phones=excluded.all_phones,all_emails=excluded.all_emails,sources=excluded.sources,updated_at=CURRENT_TIMESTAMP").bind(...lead).run();out.push({...row,"Normalized Phones":phones,"Validated Emails":emails,"QikReach Sources":"uploaded spreadsheet"})}const o=XLSX.utils.book_new();XLSX.utils.book_append_sheet(o,XLSX.utils.json_to_sheet(out),"Enriched Leads");return new Response(XLSX.write(o,{bookType:"xlsx",type:"array"}),{headers:{"content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename="qikreach-enriched-${Date.now()}.xlsx"`}})}return J({error:"Not found"},404)}
export default{async fetch(r:Request,e:Env){try{const u=new URL(r.url);if(!e.QIKREACH_PASSWORD||!e.QIKREACH_SESSION_SECRET)return new Response("Missing required secrets",{status:500});if(u.pathname==="/login"&&r.method==="POST"){const f=await r.formData();if(C(f.get("username"))!==e.QIKREACH_USERNAME||C(f.get("password"))!==e.QIKREACH_PASSWORD)return Response.redirect(new URL("/?error=1",u),303);const exp=Math.floor(Date.now()/1000)+43200,body=`${e.QIKREACH_USERNAME}|${exp}`,token=`${body}|${await mac(e.QIKREACH_SESSION_SECRET,body)}`;return new Response(null,{status:303,headers:{location:"/","set-cookie":`qikreach_session=${encodeURIComponent(token)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`}})}if(u.pathname==="/logout")return new Response(null,{status:303,headers:{location:"/","set-cookie":"qikreach_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0"}});if(u.pathname.startsWith("/api/"))return api(r,e,u);if(!await auth(r,e))return e.ASSETS.fetch(new Request(new URL("/login.html",u).toString(),r));return e.ASSETS.fetch(r)}catch(error){const message=error instanceof Error?error.message:"Unexpected worker error";return J({error:message},500)}}} satisfies ExportedHandler<Env>;
